### ISSUE TITLE
Website and api uses cloudflare

### ISSUE THREAD

**Issue by magmaus3** [KilledMufasa/AmputatorBot#14]
Hello, 
I've noticed that the website and the api uses cloudflare.

This is an issue due to the issues with the way cloudflare works, the fact that the site is inaccessible through Tor, and the general issues related to privacy.

See http://crimeflare.eu.org for more information.

**Comment by jvdburgh** [comment]
Hi there,

Thanks for your patience and for raising this concern. I totally get where you're coming from with the Cloudflare issue. Privacy and accessibility are really important, and I don't take them lightly.

In the past, I tried running things without Cloudflare, but my API got hammered with requests and it just couldn't keep up. Cloudflare offers some handy rate-limiting tools for free, and they've done a solid job so far.

I realize that Cloudflare isn't perfect and there are valid concerns around it, but overall, it seems to be doing more good for the project than harm. If I find a better alternative that can handle the load, doesn't cost an arm and a leg, and addresses the privacy issues, I'll definitely consider it.

Sorry if this isn't the answer you were hoping for, but I really do appreciate you bringing this up. It's discussions like these that help make the web a better place.

Cheers!
