### ISSUE TITLE
Online version not working due to full storage at PythonAnywhere

### ISSUE THREAD

**Issue by Felix-Pedro** [KilledMufasa/AmputatorBot#15]
Hey I've been trying to reach the online version for a while and I'm getting the same error, have you also noti
![Screenshot_20221117-084223_Chrome](https://user-images.githubusercontent.com/77068053/202439100-fde0315c-780a-41ed-aec2-5e3d350a6fba.png)
ced!?

**Comment by KilledMufasa** [comment]
Oops, sorry about that, thx for the report! 

Looks like I found the problem: I ran out of storage quota at my host PythonAnywhere. I've now upgraded my account and restarted the webapp service, after which https://www.amputatorbot.com came back online. At this time, I have no reason to believe the API or bots stopped working too at any point - only the site. 

Please let me know if it works again on your end too and thanks for letting me know about this issue :)

Cheers, Joris

**Comment by KilledMufasa** [comment]
Keeping the issue for a bit in case other or similar reports come in.

**Comment by KilledMufasa** [comment]
No new reports and everything seems to be working as should, so closing this issue for real this time :)
