### ISSUE TITLE
Config template doesn't contain sample headers

### ISSUE THREAD

**Issue by gschizas** [KilledMufasa/AmputatorBot#5]
In the function [random_headers](https://github.com/KilledMufasa/AmputatorBot/blob/master/check_comments.py#L47) there's a reference to a `config.headers` field, which doesn't exist inside the [template_config](https://github.com/KilledMufasa/AmputatorBot/blob/master/template_config.py) file, therefore you can't really run any script.

Even though the implementation should be trivial, it would be better if the sample list of headers actually existed in the template.

**Comment by KilledMufasa** [comment]
Makes sense, I've [added some example headers](https://github.com/KilledMufasa/AmputatorBot/commit/9eb1318b4b7dce5836a2bd560d02930a5dfd20f4) in the file (tbh I just forgot about it).

I then [added](https://github.com/KilledMufasa/AmputatorBot/commit/6a4834943ff6b586f7613de42f0533c522955b3e) some more info about the user-agents and which ones to use.

I also renamed the file from template_config.py to config.py to make it easier to understand.

**Comment by gschizas** [comment]
Yes, I think that's good enough. Some documentation on where to find a few of the latest user agents would help as well.
